# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|


  config.vm.define "centos7", primary: true do |centos7|
      centos7.vm.box = "centos7"
      centos7.vm.hostname = "airflow.dev7"
      centos7.vm.network "private_network", ip: "19.168.33.14"
      centos7.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.memory = "2024"
      end
      centos7.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/me.pub"
      centos7.vm.provision "shell", inline: <<-SHELL
            cat /home/vagrant/.ssh/me.pub >> /home/vagrant/.ssh/authorized_keys
            mkdir -p /root/.ssh
            cat /home/vagrant/.ssh/me.pub >> /root/.ssh/authorized_keys
      SHELL
  end

  config.vm.define "centos8", primary: true do |centos8|
      centos8.vm.box = "centos/8"
      centos8.vm.hostname = "airflow.dev8"
      centos8.vm.network "private_network", ip: "19.168.33.15"
      centos8.vm.provider "virtualbox" do |vb|
          vb.gui = false
          vb.memory = "2024"
      end
      centos8.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/me.pub"
      centos8.vm.provision "shell", inline: <<-SHELL
            cat /home/vagrant/.ssh/me.pub >> /home/vagrant/.ssh/authorized_keys
            mkdir -p /root/.ssh
            cat /home/vagrant/.ssh/me.pub >> /root/.ssh/authorized_keys
      SHELL
  end
end
