---
    - hosts: all
      gather_facts: true
      tasks:
          - debug:
                msg: '{{ ansible_distribution_major_version }}'
          - shell: yum install -y vi
            register: yum_worked
            ignore_errors: true
          - debug:
                msg: '{{ yum_worked.rc }}'
            when: yum_worked.rc != 0
