---
- hosts: all
  gather_facts: true
  tasks:

    - name: Connect to postgres and create superset user and db
      vars:
        - ansible_python_interpreter: /home/{{ superset_sys_user }}/venv/bin/python3
      postgresql_user:
        name: '{{ postgresql.superset_user }}'
        password: '{{ postgresql.superset_password }}'
        db: '{{ postgresql.superset_db }}'
        priv: ALL
        state: present
      register: postgres_user

    - debug: var=postgres_user







- name: Copy packages to the host
  copy:
    src: packages/centos{{ ansible_distribution_major_version }}/packages
    dest: /tmp/
    owner: root
    group: root

    directory_mode: 0755
