---
superset_sys_user: superset
superset_sys_password: superset

superset_admin_username: admin
superset_admin_password: admin
superset_admin_firstname: Admin
superset_admin_lastname: User
superset_admin_email: admin@admin.com

superset_load_examples: false

superset_host: 0.0.0.0
superset_port: 8088


postgresql:
    superset_user: superset
    superset_password: superset
    superset_db: superset
