
- hosts: all
  gather_facts: yes
  tasks:
    - debug:
        msg: "{{ ansible_distribution_major_version }}"
    - shell: yum install -y vi
      register: yum_worked
      ignore_errors: yes
    - debug:
        msg: "{{ yum_worked.rc }}"
      when: yum_worked.rc != 0
